dependencies:
- name: gotestnewbuildpack2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: gotestnewbuildpack3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
