dependencies:
- name: gkessotestcjxd612
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: gogketestcjxd61
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: gotestnewbuildpack2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: gotestssonew1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: ssotestgogke2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
